let clothingData = [
  {
    id: 1,
    name: "Colour Tshirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "./images/image1.png",
    price: 25,
  },
  {
    id: 2,
    name: "Formal Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "./images/image2.png",
    price: 45,
  },
  {
    id: 3,
    name: "White Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image3.png",
    price: 35,
  },
  {
    id: 4,
    name: "Causual shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image4.png",
    price: 19,
  },
  {
    id: 5,
    name: "White Tshirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image5.png",
    price: 25,
  },
  {
    id: 6,
    name: "Wollen Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image6.png",
    price: 45,
  },
  {
    id: 7,
    name: "Plade Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image7.png",
    price: 35,
  },
  {
    id: 8,
    name: "Mens suits",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image8.png",
    price: 19,
  },
  {
    id: 9,
    name: "Green mens Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image9.png",
    price: 25,
  },
  {
    id: 10,
    name: "Formal Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image10.png",
    price: 45,
  },
  {
    id: 11,
    name: "White Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image11.png",
    price: 35,
  },
  {
    id: 12,
    name: "Mens Suits",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image12.png",
    price: 19,
  },
  {
    id: 13,
    name: "Blue Tie",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image13.png",
    price: 25,
  },
  {
    id: 14,
    name: "Casual Shoes",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image14.png",
    price: 45,
  },
  {
    id: 15,
    name: "Mens Suits",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image15.png",
    price: 35,
  },
  {
    id: 16,
    name: "Casual tshirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image16.png",
    price: 19,
  },
  {
    id: 17,
    name: "Jeans Shirt",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image17.png",
    price: 25,
  },
  {
    id: 18,
    name: "Levi Pants",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image18.png",
    price: 45,
  },
  {
    id: 19,
    name: "Sports cap",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image19.png",
    price: 35,
  },
  {
    id: 20,
    name: "Leather Shoes",
    desc: "Lorem ipsum dolor sit amet, consectetur adipisicing elit.",
    image: "/images/image20.png",
    price: 19,
  },
];
